apiVersion: v1
kind: PersistentVolume
metadata:
  name: kdvops-pv
spec:
  capacity: { storage: 1Gi }
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath: { path: /srv/downloads/rpms }
