apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kdvops-pvc
  namespace: kdvops-ns
spec:
  accessModes: ["ReadWriteMany"]
  resources: { requests: { storage: 1Gi } }
  storageClassName: ""
  volumeName: kdvops-pv
